### ISSUE TITLE
Can't download data folder

### ISSUE THREAD

**Issue by Felix0805** [xgeric/UCPhrase-exp#1]
The data folder download website can't be opened

**Comment by xgeric** [comment]
Hi, it seems to be working from our side. The direct [link](https://www.dropbox.com/s/1bv7dnjawykjsji/data.zip?dl=0) also seems to be pointing to the right dropbox page. Could you please share the error information you got from running the wget command or clicking the link?

**Comment by Felix0805** [comment]
Thanks for your reply, I solve it by using a VPN.

**Comment by nlp4whp** [comment]
> Hi, it seems to be working from our side. The direct [link](https://www.dropbox.com/s/1bv7dnjawykjsji/data.zip?dl=0) also seems to be pointing to the right dropbox page. Could you please share the error information you got from running the wget command or clicking the link?

could you please share `data.zip` by other driver, cause dropbox cannot be accessed in China, :(
or  just a sample of data showing format of those data files

**Comment by xgeric** [comment]
> > Hi, it seems to be working from our side. The direct [link](https://www.dropbox.com/s/1bv7dnjawykjsji/data.zip?dl=0) also seems to be pointing to the right dropbox page. Could you please share the error information you got from running the wget command or clicking the link?
> 
> could you please share `data.zip` by other driver, cause dropbox cannot be accessed in China, :( or just a sample of data showing format of those data files

Fully understand... Unfortunately I also suffer from Baidu wangpan... Is there a good alternative?

I have uploaded the devdata folder for now, which should be sufficient for an example pass through the pipeline. Please let me know if it works!

**Comment by nlp4whp** [comment]
> > > Hi, it seems to be working from our side. The direct [link](https://www.dropbox.com/s/1bv7dnjawykjsji/data.zip?dl=0) also seems to be pointing to the right dropbox page. Could you please share the error information you got from running the wget command or clicking the link?
> > 
> > 
> > could you please share `data.zip` by other driver, cause dropbox cannot be accessed in China, :( or just a sample of data showing format of those data files
> 
> Fully understand... Unfortunately I also suffer from Baidu wangpan... Is there a good alternative?
> 
> I have uploaded the devdata folder for now, which should be sufficient for an example pass through the pipeline. Please let me know if it works!

It works, it really saves me a lot of time.  THANK YOU SO MUCH
