### ISSUE TITLE
The dataset cannot be downloaded

### ISSUE THREAD

**Issue by MinsGoing** [xgeric/UCPhrase-exp#12]
The dataset cannot be downloaded

**Comment by xgeric** [comment]
Sorry I accidentally removed it. Now it should be recovered. Please try again and let me know if the issue still exists. Sorry for the inconvenience!

**Comment by MinsGoing** [comment]
It can be downloaded. Thank you for your reply and wish you continue to publish excellent papers.

**Comment by zdaiot** [comment]
@xgeric The link is dead again. Could you open it again, please?

**Comment by Raywoo1** [comment]
> It can be downloaded. Thank you for your reply and wish you continue to publish excellent papers.

hi, mingsgoing, the link is dead again. Can you send the data for me? Please, thanks very much.
