### ISSUE TITLE
Can cpu run this code?

### ISSUE THREAD

**Issue by maruitao** [xgeric/UCPhrase-exp#3]
Can cpu run this code?
and 
How to run ？

**Comment by xgeric** [comment]
Yes, you can run the code on CPU by removing the gpu arg:

`python exp.py --dir_data ../data/devdata`

The training and inference can be slow on CPU though. Please have a try and let us know if you might come across any problems!

**Comment by maruitao** [comment]
when I run the code, I come across this problems:

  File "exp.py", line 28
    self.exp_name = f'{consts.DIR_DATA.stem}-{consts.LM_NAME_SUFFIX}-{self.path_model_config.stem}'
                                                                                                  ^
SyntaxError: invalid syntax

could you please help me to fix the code and run it correctly?   Thx

**Comment by xgeric** [comment]
Hi, which version of Python are you using? f-string is not supported in some previous versions, so please use python 3.6+ to see if the error goes away.

**Comment by maruitao** [comment]
Thx a lot!
I use python3.8.5  successfully solved this problem, but when I run the code by cpu, it come across this problem:
Traceback (most recent call last):
  File "exp.py", line 11, in <module>
    from preprocess import Preprocessor
  File "/data/WORKSPACE/UCPhrase-exp-master/src/preprocess/__init__.py", line 3, in <module>
    from preprocess.annotator_wiki import WikiAnnotator
  File "/data/WORKSPACE/UCPhrase-exp-master/src/preprocess/annotator_wiki.py", line 5, in <module>
    from match import KeywordProcessor
  File "/data/WORKSPACE/UCPhrase-exp-master/src/match/__init__.py", line 1, in <module>
    from match.keywordprocessor import KeywordProcessor
ModuleNotFoundError: No module named 'match.keywordprocessor'

If you suspect this is an IPython 7.23.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by xgeric** [comment]
Hi, did you successfully run the command `bash build.sh`? Ideally there should be a "src/match/keywordprocessor.so" file after compilation. Could you please confirm that?

**Comment by chansonzhang** [comment]
@xgeric can we build keywordprocessor on windows?

**Comment by xgeric** [comment]
Hi, we did not test the code on Windows, and we recommend to run the code on Linux.

**Comment by SaraAmd** [comment]
@maruitao I get the same error. ("ModuleNotFoundError: No module named 'match.keywordprocessor'"). Did you manage to fix it?
