### ISSUE TITLE
How to extract phrase by using stanfordcoreNLP tool?

### ISSUE THREAD

**Issue by yangjingyi** [xgeric/UCPhrase-exp#7]
Hi,

Thanks for opening your code for this paper.
I read your paper and I found that you compared your results with pretrained model such as stanfordNLP. I am curious about how to extract phrases/mentions by stanfordNLP. Do you use "coref" annotator to get coreferent mentions as extracted phrase? Or there are other tools based on stanfordCoreNLP?

Wait for your reply.

Thanks in advance.

**Comment by ZihanWangKi** [comment]
We used an approximation of noun phrases indicated by StanfordNLP's POS tagger. We further did some post-processing to remove some conjunctions such as 'a' and 'the'.

**Comment by yangjingyi** [comment]
> We used an approximation of noun phrases indicated by StanfordNLP's POS tagger. We further did some post-processing to remove some conjunctions such as 'a' and 'the'.

Do you use some rules such as determiner+adjectives+noun to select noun phrases?

**Comment by ZihanWangKi** [comment]
Sorry for the late reply. In Stanford NLP, we used the parsing tree to find the smallest NP unit and removed prefixes like "the/a" for consistent comparison.
