### ISSUE TITLE
results interpretation

### ISSUE THREAD

**Issue by icanfast** [xgeric/UCPhrase-exp#8]
This might be a repeat, but I didn't find an answer. 
Could you please specify where can I find actual resulting phrases after running the code?
I scanned the code and all the configs multiple times, but i don't see it.
Unless it's the spans in Attmap.cs_roberta_base.3layers, but in that case i'm lost at trying to interpret it.
Cheers!

Edit: I checked devdata-cs_roberta_base-core.CNN.3layers/model and these spans make much more sense, still could you please confirm those are the ones and how do I interpret them?

**Comment by xgeric** [comment]
Hi, 

Sorry for the inconvenience, as it was messy experimental code with little comments..

The result files you are looking for are organized under `experiments/${expname}/model`:

- `kpcand.decoded.epoch-${best_epoch}/eval.doc2cands-xxx.json`
  - results of document-level candidate phrase extraction in the form of "docid": [phrases].
  - these phrases serve as the candidates of the phrase ranking phase for keyphrase extraction.
- `tagging.decoded.epoch-${best_epoch}/doc2sents-xxx.json`
  - results of sentence-level phrase tagging in the form of a dictionary.
  - Each key is a document id.
  - The value is a list of sentences in the document. 
  - Each sentence consists of its tokenized wordpieces ("tokens"), and the tagged phrases ("spans").
  - Each span is a tuple of (start_token_index, end_token_index, surface_string).

Please have a look and let me know if you may have any further questions!

**Comment by icanfast** [comment]
Thank you for the answers! That confirms my assumptions.
I will try to run this with my own corpus and report any significant roadbumps if i find any.
